defmodule Tunez.Repo.Migrations.AddAlbumTracks2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:tracks, "tracks_album_id_fkey")

    alter table(:tracks) do
      modify :album_id,
             references(:albums,
               column: :id,
               name: "tracks_album_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:tracks, [:album_id])
  end

  def down do
    drop_if_exists index(:tracks, [:album_id])

    drop constraint(:tracks, "tracks_album_id_fkey")

    alter table(:tracks) do
      modify :album_id,
             references(:albums,
               column: :id,
               name: "tracks_album_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
